import argparse
import os
from os import path
import shutil
from subprocess import CalledProcessError, run
import time

from impl.benchmark_builder import BenchmarkBuilder
from impl.utils import (
    gen_result_paths,
    get_bmk_dirs,
    load_smt_model,
    prepare_subfolder,
    prepare_subfolder_with_versioning,
    resolve_project_name,
    update_record,
    ZFILL_SIZE,
)
# from impl.ityfuzz import ityfuzz_test

parser = argparse.ArgumentParser()

parser.add_argument(
    "-i",
    "--input",
    type=str,
    action="append",
    help="Input benchmark directory. Set to `all` for all of benchmarks.",
    required=True,
)

# Actions, select one of them.
parser.add_argument(
    "-p",
    "--prepare",
    help="Prepare all sol files to execute.",
    action="store_true",
)

parser.add_argument(
    "-v",
    "--verify",
    help="Verify the result of sketch.",
    action="store_true",
)

parser.add_argument(
    "-vr",
    "--verify-result-path",
    help="The result path of verification.",
    default="",
)

parser.add_argument(
    "-ha",
    "--halmos",
    help="Do Halmos symbolic execution.",
    action="store_true",
)

parser.add_argument(
    "-e",
    "--eurus",
    help="Use Eurus to solve generated candidates.",
    action="store_true",
)

parser.add_argument(
    "--fixed",
    help="The false-prositive ablation study for eurus. Sketches include vulnerable functions will be pruned.",
    action="store_true",
)

parser.add_argument(
    "-s",
    "--statistic",
    help="Print statistic.",
    action="store_true",
)

parser.add_argument(
    "-ps",
    "--printsmt",
    help="Print SMTQuery generated by Halmos",
    action="store_true",
)

parser.add_argument(
    "--tfg",
    help="Path to a single TFG JSON file to process.",
    type=str,
    default="",
)

parser.add_argument(
    "--tfg-output-bmk",
    help="Optional benchmark dir to write candidates/record when using --tfg (e.g. benchmarks/AES).",
    type=str,
    default="",
)

# Parameters for evaluation.
parser.add_argument(
    "--timeout",
    help="Set the timeout for each sketch.",
    type=int,
    default=300 * 1000,
)

parser.add_argument(
    "--start",
    help="Start sketch.",
    type=int,
    default=0,
)

parser.add_argument(
    "--end",
    help="End sketch",
    type=int,
    default=100,
)

parser.add_argument(
    "--smtdiv",
    help="Apply smt-div in which phases",
    choices=[
        "All",
        "Models",
        "None",
    ],
    default="All",
)

parser.add_argument(
    "--suffix",
    help="Special suffix to output",
    default="",
)

parser.add_argument(
    "--unsat-core",
    help="Use unsat-core based solution",
    action="store_true",
)

parser.add_argument(
    "--solver",
    help="Used Solver",
    choices=["z3"],
    default="z3",
)


def prepare(bmk_dir: str, use_versioning: bool = True):
    project_name = resolve_project_name(bmk_dir)
    if use_versioning:
        cache_path, result_path = prepare_subfolder_with_versioning(bmk_dir)
    else:
        cache_path, result_path = prepare_subfolder(bmk_dir)
    output_file = path.join(bmk_dir, f"{project_name}.t.sol")
    print(f"Output path is: {output_file}")
    builder = BenchmarkBuilder(bmk_dir, sketch_generation=True)
    builder.output(output_file)

    # Format
    cmd = [
        "npx",
        "prettier",
        "--write",
        "--plugin=prettier-plugin-solidity",
        f"{output_file}",
    ]
    run(cmd, text=True, check=True)

    # Run ground truth
    # cmds = [
    #     "forge",
    #     "test",
    #     "-vv",
    #     "--cache-path",
    #     cache_path,
    #     "--match-path",
    #     output_file,
    #     "--extra-output",
    #     "storageLayout",
    #     "metadata",
    #     "--root",
    #     os.getcwd(),
    # ]
    # print("Execute: ", " ".join(cmds))
    # try:
    #     out = run(cmds, text=True, check=True, capture_output=True)
    # except Exception as err:
    #     if isinstance(err, CalledProcessError):
    #         print(err.stderr, err.stdout)
    #     print(f"\n\nBenchmark: {bmk_dir} ground truth doesn't work!")
    #     raise err

    # Generate Candidates

    output_file = path.join(bmk_dir, f"{project_name}_candidates.t.sol")

    candidates, timecost = builder.output_with_candidates(output_file)

    candidate_strs = [c.func_sigs for c in candidates]

    gen_candidate = {"sketchgen_timecost": timecost, "candidates": candidate_strs}

    update_record(result_path, gen_candidate)

    # Format
    cmd = [
        "npx",
        "prettier",
        "--write",
        "--plugin=prettier-plugin-solidity",
        f"{output_file}",
    ]
    run(cmd, text=True, check=True)

def verify_result(bmk_dir: str, smtdiv: str, verify_result_path: str, suffix_spec: str):
    from impl.verifier import verify_model

    builder = BenchmarkBuilder(bmk_dir)
    synthesizer = builder.synthesizer
    _, result_path = prepare_subfolder(bmk_dir)
    project_name = resolve_project_name(bmk_dir)

    result_paths = gen_result_paths(result_path, smtdiv, len(synthesizer.candidates), suffix_spec)

    verifiers = []

    for func_name, output_path, _, _ in result_paths:
        output_path = verify_result_path if verify_result_path != "" else output_path
        sketch = builder.get_sketch_by_func_name(func_name, synthesizer.candidates)
        model = load_smt_model(output_path)
        if len(model) == 0:
            continue
        verifiers.append((func_name, sketch, model))

    succeed = verify_model(bmk_dir, verifiers)
    if succeed:
        print(f"Great! Benchmark: {project_name} is solved by setting: smtdiv={smtdiv}")
    else:
        print(f"Benchmark: {project_name} is NOT solved by setting: smtdiv={smtdiv}")
    return succeed


def halmos_test(
    bmk_dir: str,
    args,
):
    from impl.halmos import exec_halmos

    timeout: int = 1800 * 1000
    start: int = args.start
    end: int = args.end
    suffix_spec: str = args.suffix
    builder = BenchmarkBuilder(bmk_dir)
    synthesizer = builder.synthesizer
    project_name = resolve_project_name(bmk_dir)
    _, result_path = prepare_subfolder(bmk_dir)

    result_paths = gen_result_paths(result_path, "halmos", len(synthesizer.candidates), suffix_spec)

    result_paths = result_paths[start:end]

    for func_name, output_path, _, _ in result_paths:
        args = [
            "-vvvvv",
            "--function",
            f"{func_name}",
            "--bmk-dir",
            f"{bmk_dir}",
            "--contract",
            f"{project_name}Test",
            "--forge-build-out",
            ".cache",
            "--print-potential-counterexample",
            "--solver-timeout-assertion",
            # 20 times for each path in Halmos
            f"{timeout}",
            "--json-output",
            output_path,
            "--smt-div",
            "--suffix",
            suffix_spec,
        ]
        print("halmos " + " ".join(args))
        exec_halmos(*args)


def _main():
    args = parser.parse_args()

    # Handle single TFG file
    if args.tfg:
        print(f"Processing single TFG file: {args.tfg}")
        if not path.exists(args.tfg):
            print(f"Error: TFG file {args.tfg} does not exist")
            return

        try:
            from impl.token_flow_graph import load_tfg_manager_from_json
            manager = load_tfg_manager_from_json(args.tfg)
            timer = time.perf_counter()
            candidates = manager.gen_candidates()
            timecost = time.perf_counter() - timer

            print(f"Generated {len(candidates)} candidates from TFG:")
            for i, candidate in enumerate(candidates[:10]):  # Show first 10
                print(f"  {i+1}. {candidate}")
            if len(candidates) > 10:
                print(f"  ... and {len(candidates) - 10} more")

            # Optional: write candidates and record into a benchmark folder,
            # so users don't need to manually copy TFG JSON into bmk dir.
            if args.tfg_output_bmk:
                bmk_dir = args.tfg_output_bmk
                project_name = resolve_project_name(bmk_dir)
                _, result_path = prepare_subfolder_with_versioning(bmk_dir)

                builder = BenchmarkBuilder(bmk_dir, sketch_generation=True)
                func_bodys = []
                for idx, c in enumerate(candidates):
                    suffix = str(idx).zfill(ZFILL_SIZE)
                    func_name = builder.check_cand_prefix + suffix
                    func_bodys.extend(c.output(func_name, builder.extra_statements))

                output_file = path.join(bmk_dir, f"{project_name}_candidates.t.sol")
                results = [
                    *builder.gen_imports(),
                    *builder.gen_contract_header("Test"),
                    *builder.gen_state_varibles(),
                    *builder.gen_setup(),
                    *builder.gen_helper_funcs(),
                    *builder.gen_actions(),
                    *func_bodys,
                    "}",
                ]
                with open(output_file, "w") as f:
                    for l in results:
                        f.write(l)
                        f.write("\n")

                candidate_strs = [c.func_sigs for c in candidates]
                update_record(
                    result_path,
                    {"sketchgen_timecost": timecost, "candidates": candidate_strs},
                )
                print(f"Wrote candidates to: {output_file}")
                print(f"Updated record: {path.join(result_path, 'record.json')}")

        except Exception as e:
            print(f"Error processing TFG: {e}")
            import traceback
            traceback.print_exc()
        return

    bmk_dirs = get_bmk_dirs(args.input)
    for bmk_dir in bmk_dirs:
        if args.prepare:
            prepare(bmk_dir)
        if args.eurus:
            from impl.eurus import eurus_test

            eurus_test(bmk_dir, args)
        if args.halmos:
            halmos_test(bmk_dir, args)
        # if args.fuzz:
        #     ityfuzz_test(bmk_dir, args)
        if args.verify:
            verify_result(bmk_dir, args.smtdiv, args.verify_result_path, args.suffix)


def clean_result(bmk_dir: str, smtdiv: str, start: int, end: int, suffix_spec: str):
    builder = BenchmarkBuilder(bmk_dir)
    synthesizer = builder.synthesizer
    _, result_path = prepare_subfolder(bmk_dir)
    result_paths = gen_result_paths(result_path, smtdiv, len(synthesizer.candidates), suffix_spec)
    result_paths = result_paths[start:end]
    for _, output_path, err_path, smt_folder in result_paths:
        if path.exists(output_path):
            os.remove(output_path)
        if path.exists(err_path):
            os.remove(err_path)
        if path.exists(smt_folder):
            shutil.rmtree(smt_folder)


if __name__ == "__main__":
    _main()
